output_dir: /home/anon/freelancing/mercor_mle/suresh-llm-judge-interview-2/llm-judge-interview-2/llm-judge-interview-2/data/mercor_mle/test-2024-05-17-00-29
llm_params:
  - gpt-4-turbo-preview:
      temperature: 0.7
      max_tokens: 100
  # - gpt-3.5-turbo-0125:
  #     temperature: 0.7
  #     prompt_modification: {"cot": "Think step by step."}
  - gpt-3.5-turbo-0125:
      temperature: 0.7

N: 1
num_workers: 4
printout_limit: 50