judge:
  class_path: llm_judge.judges.BaselineComparisonJudge
  init_args:
    baseline_llm: gpt-3.5-turbo-0125
    judge_prompts: {"system": "662813e0e25b6076a9e03df8", "prompt_template": "662821e23eb9ef01018e30e2", "reversed_prompt_template": "6628224eb84c0693351ca6a4"}
    judge_llm: gpt-4-turbo-preview
    judge_llm_params: {"temperature": 0, "max_tokens": 1000}

N: 1
output_dir: /Users/amymartian/Projects/router-judge/runs/deepAI/run-april24
num_workers: 50
printout_limit: 50