output_dir: /Users/amymartian/Projects/router-judge/runs/deepAI/run-april24
llm_params:
  - gpt-4-turbo-preview:
      temperature: 0.7
      max_tokens: 100
  - gpt-3.5-turbo-0125:
      temperature: 0.7
      prompt_modification: {"cot": "Think step by step."}
  - gpt-3.5-turbo-0125:
      temperature: 0.7

N: 1
num_workers: 5
printout_limit: 50